### ISSUE TITLE
Common code review issues

### ISSUE THREAD

**Issue by dmitry-weirdo** [dmatveyev/ConsoleChat#10]
- Добавить .gitignore, где, как минимум, заигнорить target-директории и *.iml файлы. 
- Убрать ``*.iml`` файлы из-под git. Любая IDE может открывать проект из pom.xml, а .iml файлы могут быть разными в разных версиях Идеи.
- В случае исключений логировать их через логгер, а не через ``printStackTrace``.
- Пользоваться автогенерацией в IDEA (Alt + Ins) для геттеров/сеттеров, конструкторов и т.д.. Не нужно писать их руками, тогда и опечаток не будет.
- В целом очень неаккуратное выравнивание кода и джавадоков. Хотя бы через Ctrl + Alt + L стоит выравнивать. Лучше, конечно, сразу писать правильно.
- Написать тест на ``MessagePool``, когда там много листнеров. Сейчас там полный пц с синхронизацией, всё будет зависать. Плюс кейс, когда нет ни одного листнера.
- Везде работать через интерфейсы, а не классы.
- Классы всяких ``*Message`` дублируются между клиентом и сервером. Стоит выделить их в некоторый common модуль, от которого будут зависеть и клиент, и сервер.
- Исправить опечатки (Идея их вполне успешно показывает). Найти все опечатки: Ctrl + Alt + Shift + I; набрать typo и выбрать его; нажать enter; убедиться, что выбран Whole project; запустить.
- Не использовать магические строки, вынести всё в константы.
- Лучше не делать всяких страшных операций вроде открытий потоков/сокетов и т.д. в конструкторах.
- Исправить Идеевские инспекции. Уже после этого код станет гораздо лучше.
- Если класс предполагается иммутабельным, и у него только геттеры, а поля заполняются в конструкторе, то поля стоит делать ``final``.  Это про классы вроде ``Message``, ``AuthMessage``, ``BroadcastMessage``.
- ``Server`` стартуется, но не останавливается? Нужно останавливать, причём, скорее всего, в ``finally``.
- ``PreparedStatement`` тоже нужно закрывать. Насколько я помню, можно написать и ``Connection`` и ``PreparedStatement`` в одном блоке try-with-resources.

**Comment by dmatveyev** [comment]
Убрал iml.
отформатировал код Ctrl + Alt + L
Добавил логирование исключений
Исправления сделаны в ветке addLogging

**Comment by dmitry-weirdo** [comment]
Куча ``e.printStackTrace()`` всё равно осталась. Нужно исправить по всему проекту.

**Comment by dmatveyev** [comment]
Добавил .gitignore
Вынес messages в отдельный модуль, добавил зависимости

**Comment by dmatveyev** [comment]
Перенёс PreparedStatement в блок try-with-resourses, но для Result set появился warning "Nested try statement...". Как его обработать грамотно?

**Comment by dmatveyev** [comment]
#12 
Пулл реквест с правками кода по корневому описанию
